#!/bin/bash
#SBATCH --mem=80GB
#SBATCH -o cameraReady_quevedo_pub14metonymy_specific.out
#SBATCH --time=01:00:00
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu
#SBATCH --account=dcs-acad6
#SBATCH --reservation=dcs-acad6
#SBATCH --qos=gpu

module load Anaconda3/2022.10
module load CUDA/10.1.243
source activate /mnt/parscratch/users/acq22zm/anaconda/.envs/surprisal
export HF_HOME=/mnt/parscratch/users/acq22zm/.cache

LD_LIBRARY_PATH=""

model="quevedo"

python ../mlp_implementations.py \
    --features cis_positional_sentenceMin_in_expression cws_phrase_mean cws_drops_within_expression cws_sentence_middle surprisal_context_max cis_drops_within_expression cis_phrase_min cws_context_median cis_sentence_sum cis_phrase_sum vanilla_entropy_phrase_min surprisal_relational_minPhrase_minSentence surprisal_phrase_max cis_relational_sumPhrase_sumSentence cis_sentence_min surprisal_sentence_sum vanilla_entropy_position_sentenceMax surprisal_position_sentenceMin cis_context_median cws_context_middle cws_relational_minPhrase_minSentence cws_spikes_within_expression vanilla_entropy_positional_sentenceMax_in_expression surprisal_context_sum cis_context_min cws_context_min cws_position_sentenceMax vanilla_entropy_context_max vanilla_entropy_relational_minPhrase_minSentence cws_phrase_min cis_relational_minPhrase_minSentence cis_position_sentenceMax surprisal_sentence_min cws_phrase_median surprisal_phrase_std cws_position_sentenceMin surprisal_phrase_min vanilla_entropy_sentence_median surprisal_position_sentenceMax cws_phrase_sum cis_sentence_median cis_phrase_median surprisal_sentence_median cws_positional_sentenceMax_in_expression surprisal_context_std cws_positional_sentenceMin_in_expression vanilla_entropy_drops_within_expression vanilla_entropy_context_median cws_sentence_std surprisal_context_median vanilla_entropy_sentence_middle cis_phrase_middle cis_position_sentenceMin surprisal_sentence_middle surprisal_positional_sentenceMin_in_expression surprisal_spikes_within_expression cws_sentence_median vanilla_entropy_relational_maxPhrase_maxSentence cws_sentence_min cws_context_mean cis_phrase_mean cis_relational_maxPhrase_maxSentence vanilla_entropy_sentence_std vanilla_entropy_sentence_min vanilla_entropy_phrase_mean cis_sentence_std cis_spikes_within_expression surprisal_sentence_std cis_positional_sentenceMax_in_expression vanilla_entropy_phrase_sum vanilla_entropy_context_middle cws_phrase_middle vanilla_entropy_phrase_max cws_context_sum cis_sentence_middle surprisal_phrase_sum cis_context_middle vanilla_entropy_phrase_std surprisal_context_middle surprisal_phrase_middle vanilla_entropy_phrase_median cws_phrase_max vanilla_entropy_context_sum cws_phrase_std surprisal_context_min cis_phrase_max cws_context_max vanilla_entropy_relational_sumPhrase_sumSentence surprisal_phrase_mean vanilla_entropy_sentence_sum surprisal_relational_maxPhrase_maxSentence cis_context_max surprisal_phrase_median cws_relational_maxPhrase_maxSentence cis_context_std cis_phrase_std cis_context_sum vanilla_entropy_context_std cws_context_std vanilla_entropy_context_min surprisal_drops_within_expression vanilla_entropy_phrase_middle vanilla_entropy_position_sentenceMin cis_context_mean vanilla_entropy_spikes_within_expression surprisal_positional_sentenceMax_in_expression vanilla_entropy_context_mean vanilla_entropy_positional_sentenceMin_in_expression cws_sentence_sum cws_relational_sumPhrase_sumSentence surprisal_relational_sumPhrase_sumSentence surprisal_context_mean\
    --model $model \
    --output_dir ../../sentence-level/cameraReady_quevedo \
    --remarks cameraReady_quevedo_pub14metonymy_specific \
    --save
