#!/bin/bash
#SBATCH --mem=80GB
#SBATCH -o cameraReady_lr_rest_specific.out
#SBATCH --time=01:00:00


module load Anaconda3/2022.10
module load CUDA/10.1.243
source activate /mnt/parscratch/users/acq22zm/anaconda/.envs/surprisal
export HF_HOME=/mnt/parscratch/users/acq22zm/.cache

LD_LIBRARY_PATH=""

model="lr"

python ../classifier.py \
    --features surprisal_phrase_mean surprisal_phrase_std surprisal_phrase_min surprisal_phrase_max surprisal_phrase_sum surprisal_phrase_middle surprisal_phrase_median surprisal_context_mean surprisal_context_std surprisal_context_min surprisal_context_max surprisal_context_sum surprisal_context_middle surprisal_context_median surprisal_phrase_head_and_tail_avg surprisal_phrase_head_and_tail_diff surprisal_boundary_phraseEnd_firstWordAfter_mean surprisal_boundary_phraseEnd_firstWordAfter_diff surprisal_position_sentenceMax surprisal_position_sentenceMin surprisal_positional_sentenceMax_in_expression surprisal_positional_sentenceMin_in_expression surprisal_relational_sumPhrase_sumSentence surprisal_relational_maxPhrase_maxSentence surprisal_relational_minPhrase_minSentence cws_phrase_mean cws_phrase_std cws_phrase_min cws_phrase_max cws_phrase_sum cws_phrase_middle cws_phrase_median cws_context_mean cws_context_std cws_context_min cws_context_max cws_context_sum cws_context_middle cws_context_median cws_phrase_head_and_tail_avg cws_phrase_head_and_tail_diff cws_boundary_phraseEnd_firstWordAfter_mean cws_boundary_phraseEnd_firstWordAfter_diff cws_position_sentenceMax cws_position_sentenceMin cws_positional_sentenceMax_in_expression cws_positional_sentenceMin_in_expression cws_relational_sumPhrase_sumSentence cws_relational_maxPhrase_maxSentence cws_relational_minPhrase_minSentence vanilla_entropy_phrase_mean vanilla_entropy_phrase_std vanilla_entropy_phrase_min vanilla_entropy_phrase_max vanilla_entropy_phrase_sum vanilla_entropy_phrase_middle vanilla_entropy_phrase_median vanilla_entropy_context_mean vanilla_entropy_context_std vanilla_entropy_context_min vanilla_entropy_context_max vanilla_entropy_context_sum vanilla_entropy_context_middle vanilla_entropy_context_median vanilla_entropy_phrase_head_and_tail_avg vanilla_entropy_phrase_head_and_tail_diff vanilla_entropy_boundary_phraseEnd_firstWordAfter_mean vanilla_entropy_boundary_phraseEnd_firstWordAfter_diff vanilla_entropy_position_sentenceMax vanilla_entropy_position_sentenceMin vanilla_entropy_positional_sentenceMax_in_expression vanilla_entropy_positional_sentenceMin_in_expression vanilla_entropy_relational_sumPhrase_sumSentence vanilla_entropy_relational_maxPhrase_maxSentence vanilla_entropy_relational_minPhrase_minSentence cis_phrase_mean cis_phrase_std cis_phrase_min cis_phrase_max cis_phrase_sum cis_phrase_middle cis_phrase_median cis_context_mean cis_context_std cis_context_min cis_context_max cis_context_sum cis_context_middle cis_context_median cis_phrase_head_and_tail_avg cis_phrase_head_and_tail_diff cis_boundary_phraseEnd_firstWordAfter_mean cis_boundary_phraseEnd_firstWordAfter_diff cis_position_sentenceMax cis_position_sentenceMin cis_positional_sentenceMax_in_expression cis_positional_sentenceMin_in_expression cis_relational_sumPhrase_sumSentence cis_relational_maxPhrase_maxSentence cis_relational_minPhrase_minSentence\
    --model $model \
    --output_dir ../../cameraReady_lr_results \
    --remarks cameraReady_lr_rest_specific \
    --save
